//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string eventId { get; set; }
        public string friendPhoneNum { get; set; }
        public string content { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
