//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public Journal()
        {
            this.Events = new HashSet<Event>();
        }
    
        public string id { get; set; }
        public string ownerPhoneNum { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> lastEditTime { get; set; }
        public string cover { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual User User { get; set; }
    }
}
