//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionInfo
    {
        public RegionInfo()
        {
            this.RegionStatistics = new HashSet<RegionStatistic>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string writing { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public Nullable<int> radius { get; set; }
    
        public virtual ICollection<RegionStatistic> RegionStatistics { get; set; }
    }
}
