//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using DAL;

namespace Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelMobileEntities : DbContext
    {
        public TravelMobileEntities()
            : base("name=TravelMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminInfo> AdminInfos { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<EmergencyCall> EmergencyCalls { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<FriendReference> FriendReferences { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public DbSet<LostContact> LostContacts { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Point> Points { get; set; }
        public DbSet<PushLog> PushLogs { get; set; }
        public DbSet<RegionInfo> RegionInfos { get; set; }
        public DbSet<RegionStatistic> RegionStatistics { get; set; }
        public DbSet<SceneInfo> SceneInfos { get; set; }
        public DbSet<ServerLog> ServerLogs { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
