//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.EmergencyCalls = new HashSet<EmergencyCall>();
            this.FriendReferences = new HashSet<FriendReference>();
            this.FriendReferences1 = new HashSet<FriendReference>();
            this.Journals = new HashSet<Journal>();
            this.LostContacts = new HashSet<LostContact>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Points = new HashSet<Point>();
        }
    
        public string phoneNum { get; set; }
        public Nullable<int> id { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string sex { get; set; }
        public byte[] avatar { get; set; }
        public Nullable<int> isInScenic { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<EmergencyCall> EmergencyCalls { get; set; }
        public virtual ICollection<FriendReference> FriendReferences { get; set; }
        public virtual ICollection<FriendReference> FriendReferences1 { get; set; }
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual ICollection<LostContact> LostContacts { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Point> Points { get; set; }
    }
}
