//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public Nullable<int> id { get; set; }
        public string phoneNum { get; set; }
        public string name { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string sex { get; set; }
        public string avatar { get; set; }
    }
}
